wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1718300677
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.10
      5: 0.17.1
      8:
      - 2
      - 5
      13: linux-x86_64
