wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1718292871
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.17.1
      8:
      - 2
      - 5
      13: linux-x86_64
alpha:
  desc: null
  value: 0.25
batch_size:
  desc: null
  value: 32
fc_layer_size:
  desc: null
  value: 512
gamma:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
